// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUw12sk61DMFoggNHoqmTbYiZU-G86RXM',
    appId: '1:532486920518:web:6368fefe8ae89c8a032d47',
    messagingSenderId: '532486920518',
    projectId: 'classia-trading',
    authDomain: 'classia-trading.firebaseapp.com',
    storageBucket: 'classia-trading.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1N99gbnlaHncVAzg4Wl88Z_6Pog4et90',
    appId: '1:532486920518:android:24d3589d45784bee032d47',
    messagingSenderId: '532486920518',
    projectId: 'classia-trading',
    storageBucket: 'classia-trading.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNhJFHtwkpwfaxRZeVw3vrVcJnu0Efbyw',
    appId: '1:532486920518:ios:29c4a104f7f0b8a0032d47',
    messagingSenderId: '532486920518',
    projectId: 'classia-trading',
    storageBucket: 'classia-trading.appspot.com',
    iosBundleId: 'com.example.classiaBroker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNhJFHtwkpwfaxRZeVw3vrVcJnu0Efbyw',
    appId: '1:532486920518:ios:29c4a104f7f0b8a0032d47',
    messagingSenderId: '532486920518',
    projectId: 'classia-trading',
    storageBucket: 'classia-trading.appspot.com',
    iosBundleId: 'com.example.classiaBroker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUw12sk61DMFoggNHoqmTbYiZU-G86RXM',
    appId: '1:532486920518:web:ef4b796996497af0032d47',
    messagingSenderId: '532486920518',
    projectId: 'classia-trading',
    authDomain: 'classia-trading.firebaseapp.com',
    storageBucket: 'classia-trading.appspot.com',
  );
}
